spring:
  application:
    name: yhapi-backed
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yhapi
    username: root
    password: abc8909389
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: none
#  文件上传大小
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  # redis 配置
#  redis:
#    port: 6379
#    host: myredis12345.redis.rds.aliyuncs.com
#    database: 0
#    password: Abc8909389
#    username: redis
server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
yhapi:
  client:
    access-key: testak
    secret-key: testsk
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
#    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
#    address: nacos://localhost:8848
#    address: nacos://101.37.167.58:8848?username=nacos&password=nacos
    address: nacos://localhost:8848?username=nacos&password=nacos


